### ISSUE TITLE
Add location to venv

### ISSUE THREAD

**Issue by Steve-Mcl** [404background/node-red-contrib-python-venv#18]
Hi, loving the progress here.

I wondered if you might consider adding support for specifying where the virtual environment lives (i.e. permit the file path to be specified)?  

Thanks for the consideration.

**Comment by 404background** [comment]
@Steve-Mcl 
In #19 , I have made the nodes can be executed even if an absolute path is specified!

![venv-config-abspath](https://github.com/404background/node-red-contrib-python-venv/assets/112294959/2531dd5b-d45d-4158-938a-6ac64b3f19df)
If you get any errors, please feel free to report them in issues.

**Comment by Steve-Mcl** [comment]
thank you for the super quick iteration.
