### ISSUE TITLE
How to stop running venv node python code from Node-RED node

### ISSUE THREAD

**Issue by corndog2000** [404background/node-red-contrib-python-venv#25]
Hello, is it possible to stop a venv node running a python program from another node-red node?

**Comment by 404background** [comment]
Thank you @corndog2000 for the question!

If you use venv node with Continuous mode, you can terminate it.
Set msg.terminate to true and send to vnev node.
This function was added in https://github.com/404background/node-red-contrib-python-venv/pull/20.
![image](https://github.com/user-attachments/assets/fe1f788b-bd07-436c-a634-008c8cf2708c)
![image](https://github.com/user-attachments/assets/8ff250d7-f159-4fa3-88d1-2ff6832d522c)

Here is the sample flow and the video. This sample stops an endless loop with while.
https://github.com/404background/node-red-contrib-python-venv/blob/main/examples/continuous.json
https://youtu.be/LKgl6cZuWXE

Sorry for the lack of explanation about the node.
I am personally busy until next week, but I will add the explanation when I have time.

**Comment by corndog2000** [comment]
Thank you for the explanation! This is just what I was looking for!
