### ISSUE TITLE
Creating Multiple Virtual Environments

### ISSUE THREAD

**Issue by 404background** [404background/node-red-contrib-python-venv#3]
For now, this node runs the program in a single Python virtual environment.
The idea is to create multiple virtual environments and make them selectable.

- Add the function to create/delete virtual environments.

**Comment by FrederikPM** [comment]
@404background are you currently working on this enhancement?

**Comment by 404background** [comment]
@FrederikPM 
Yes, I was working on the following branch today.
[3-creating-multiple-virtual-environments](https://github.com/404background/node-red-contrib-python-venv/tree/3-creating-multiple-virtual-environments)

I added a configuration node.
I am trying with oneditsave to be able to create a new virtual environment when the configuration node is updated.
![image](https://github.com/404background/node-red-contrib-python-venv/assets/112294959/d8b82210-10f8-4f41-895f-fc48c03b7b27)

I always use py.exe when I specify version of python.
So I'm testing it so that I can also specify the version for Windows.
![image](https://github.com/404background/node-red-contrib-python-venv/assets/112294959/eaed0a25-4980-4687-97fe-296568a67336)

I am still thinking about how to implement this.
I would like to hear any opinions!

**Comment by FrederikPM** [comment]
I think what you are doing is makes sense. I was considering that it would be practical to handle the selection, creation, editing, and deletion of environments similarly to how @Alkarex manages server connections in his (https://github.com/alexandrainst/node-red-contrib-postgresql).

This interaction would then make sense to be reused in both the pip and venv node.
