### ISSUE TITLE
input for venv node

### ISSUE THREAD

**Issue by agustinvinao** [404background/node-red-contrib-python-venv#4]
Hi, great work, simple and fast! congrats.

I don't see a way to access input data for the node. If is not supported yet will be great to have it.

thanks

**Comment by 404background** [comment]
Thank you @agustinvinao !

Now, if the Code in the venv node is blank, the msg.code is saved in a tmp file.

It would certainly be useful to have access to the input data.
I will try to make it possible to access JSON format objects such as msg, flow, global, etc.

**Comment by Alkarex** [comment]
Please check https://github.com/404background/node-red-contrib-python-venv/pull/6

**Comment by 404background** [comment]
@agustinvinao 
We can now access input data for this node!

Thank you @Alkarex !
And when I changed msg, I could access other properties.
I think we can now access values other than payload.

![msg-property](https://github.com/404background/node-red-contrib-python-venv/assets/112294959/59bae560-0e59-4f7e-aa75-185d73828f89)

**Comment by Alkarex** [comment]
Right now, only `msg.payload` is passed as input.
Note for later: other PRs should address the case of running in a folder path that contains a space
