### ISSUE TITLE
Setup GitHub Sponsor Feature

### ISSUE THREAD

**Issue by corndog2000** [404background/node-red-contrib-python-venv#43]
Hello, I use this project extensively at my work. I'd love to give back if possible.

**Comment by 404background** [comment]
Thank you @corndog2000 for the suggestion!

And thank you for using this node.
Not many people around me are using this node, so I'm always concerned about whether it's working properly.

I have never set up a GitHub Sponsor, but I will try it.
I am curious to see how everyone is utilizing this node, so I would like to set up a page where we can share it.

**Comment by 404background** [comment]
I have set up a GitHub Sponsor!

**Comment by corndog2000** [comment]
I use this node extensively in this robotic platform at my university. I am the engineer behind the platform. I use your node for running python scripts that run measurements for the 4-point probe and for the UV-VIS/NIR Ocean Optics spectrometer.

[https://youtu.be/S9GmWnBYgwM](https://youtu.be/S9GmWnBYgwM)

**Comment by 404background** [comment]
Thank you @corndog2000 !

I am also using robots in my university research.
In the future, our research aims to automate agricultural robotics.
I use Node-RED to connect Unreal Engine and ROS, and also run it in Python to detect objects with YOLO.
https://qiita.com/background/items/b051fcebba3f67e8c7d8

I have set up a GitHub Discussion page where we can share ideas and flows.
If you are interested, please visit the site!
https://github.com/404background/node-red-contrib-python-venv/discussions
